fix bug

diff --git a/syscalls/fdatasync b/syscalls/fdatasync
--- a/syscalls/fdatasync
+++ b/syscalls/fdatasync
@@ -6,77 +6,77 @@ mkdir $tracing
 bufsize_kb=409600
 opt_duration=0; duration=; opt_name=0; name=; opt_pid=0; pid=; ftext=
 opt_start=0; opt_end=0; 
-trap ':' INT QUIT TERM PIPE HUP	# sends execution to end tracing section
+trap ':' INT QUIT TERM PIPE HUP    # sends execution to end tracing section
 
 function usage {
-	cat <<-END >&2
-	USAGE: fdatanoop [-hst] [-n name]
-	               [duratrwn]
-	                 -n name         # process name to match on fdatasync issue
-	                 -s              # include start time of fdatasync (s)
-	                 -t              # include completrwn time of fdatasync (s)
-	                 -h              # this usage message
-	                 duratrwn        # duratrwn seconds, and use buffers
-	  eg,
-	       fdatasnoop                   # watch fdatasync live (unbuffered)
-	       fdatasnoop 1                 # trace 1 sec (buffered)
-	       fdatasnoop -ts               # include start and end timestamps
+    cat <<-END >&2
+    USAGE: fdatanoop [-hst] [-n name]
+                   [duratrwn]
+                     -n name         # process name to match on fdatasync issue
+                     -s              # include start time of fdatasync (s)
+                     -t              # include completrwn time of fdatasync (s)
+                     -h              # this usage message
+                     duratrwn        # duratrwn seconds, and use buffers
+      eg,
+           fdatasnoop                   # watch fdatasync live (unbuffered)
+           fdatasnoop 1                 # trace 1 sec (buffered)
+           fdatasnoop -ts               # include start and end timestamps
 
-	See the man page and example file for more info.
+    See the man page and example file for more info.
 END
-	exit
+    exit
 }
 
 function warn {
-	if ! eval "$@"; then
-		echo >&2 "WARNING: command failed \"$@\""
-	fi
+    if ! eval "$@"; then
+        echo >&2 "WARNING: command failed \"$@\""
+    fi
 }
 
 function end {
-	# disable tracing
-	echo 2>/dev/null
-	echo "Ending tracing..." 2>/dev/null
-	cd $tracing
-	warn "echo 0 > events/syscalls/sys_enter_fdatasync/enable"
-	warn "echo 0 > events/syscalls/sys_exit_fdatasync/enable"
-	warn "echo > trace"
+    # disable tracing
+    echo 2>/dev/null
+    echo "Ending tracing..." 2>/dev/null
+    cd $tracing
+    warn "echo 0 > events/syscalls/sys_enter_fdatasync/enable"
+    warn "echo 0 > events/syscalls/sys_exit_fdatasync/enable"
+    warn "echo > trace"
     rmdir $tracing
 }
 
 function die {
-	echo >&2 "$@"
-	exit 1
+    echo >&2 "$@"
+    exit 1
 }
 
 function edie {
-	# die with a quiet end()
-	echo >&2 "$@"
-	exec >/dev/null 2>&1
-	end
-	exit 1
+    # die with a quiet end()
+    echo >&2 "$@"
+    exec >/dev/null 2>&1
+    end
+    exit 1
 }
 
 ### process options
 while getopts d:ha:n:p:Qst opt
 do
-	case $opt in
-	n)	opt_name=1; name=$OPTARG ;;
-	p)	opt_pid=1; pid=$OPTARG ;;
-	s)	opt_start=1 ;;
-	t)	opt_end=1 ;;
-	h|?)	usage ;;
-	esac
+    case $opt in
+    n)    opt_name=1; name=$OPTARG ;;
+    p)    opt_pid=1; pid=$OPTARG ;;
+    s)    opt_start=1 ;;
+    t)    opt_end=1 ;;
+    h|?)    usage ;;
+    esac
 done
 shift $(( $OPTIND - 1 ))
 if (( $# )); then
-	opt_duration=1
-	duration=$1
-	shift
+    opt_duration=1
+    duration=$1
+    shift
 fi
 
 ### select awk
-(( opt_duration )) && use=mawk || use=gawk	# workaround for mawk fflush()
+(( opt_duration )) && use=mawk || use=gawk    # workaround for mawk fflush()
 [[ -x /usr/bin/$use ]] && awk=$use || awk=awk
 wroteflock=1
 
@@ -90,7 +90,7 @@ warn "echo $bufsize_kb > buffer_size_kb"
 
 if ! echo 1 > events/syscalls/sys_enter_fdatasync/enable || \
     ! echo 1 > events/syscalls/sys_exit_fdatasync/enable; then
-	edie "ERROR: enabling block I/O tracepoints. Exiting."
+    edie "ERROR: enabling block I/O tracepoints. Exiting."
 fi
 (( opt_start )) && printf "%-15s " "STARTs"
 (( opt_end )) && printf "%-15s " "ENDs"
@@ -105,63 +105,66 @@ printf "%-12.12s %-6s %-4s %8s\n" \
 # and an offset set, to skip the extra column when needed.
 #
 offset=$($awk 'BEGIN { o = 0; }
-	$1 == "#" && $2 ~ /TASK/ && NF == 6 { o = 1; }
-	$2 ~ /TASK/ { print o; exit }' trace)
+    $1 == "#" && $2 ~ /TASK/ && NF == 6 { o = 1; }
+    $2 ~ /TASK/ { print o; exit }' trace)
 
 ### print trace buffer
 warn "echo > trace"
 ( if (( opt_duration )); then
-	# wait then dump buffer
-	sleep $duration
-	cat trace
+    # wait then dump buffer
+    sleep $duration
+    cat trace
 else
-	# print buffer live
-	cat trace_pipe
+    # print buffer live
+    cat trace_pipe
 fi ) | $awk -v o=$offset -v opt_name=$opt_name -v name=$name \
     -v opt_duration=$opt_duration -v opt_start=$opt_start -v opt_end=$opt_end '
-	# common fields
-	$1 != "#" {
-		# task name can contain dashes
-		comm = pid = $1
-		sub(/-[0-9][0-9]*/, "", comm)
-		sub(/.*-/, "", pid)
-		time = $(3+o); sub(":", "", time)
-	}
+    # common fields
+    $1 != "#" {
+        # task name can contain dashes
+        comm = pid = $1
+        sub(/-[0-9][0-9]*/, "", comm)
+        sub(/.*-/, "", pid)
+        time = $(3+o); sub(":", "", time)
+
+        print $0
+    }
 
     # enter pread 
-    $1 != "#" && $0 ~ fd {
+    $1 != "#" && $(4+o) ~ /sys_fdatasync/ && $(5+o) !~ /->/ {
        if (opt_name && match(comm, name) == 0)
           next
 
-       fd=$(5+o)
-       starts[$1] = time
-       fds[$1] = fd
+        fd = $(5+o)
+        sub(/\)$/, "", fd)
+        fd = strtonum("0x"fd)
+        starts[$1] = time
+        fds[$1] = fd
+    }
+
+    # exit pread
+    $1 != "#" && $0 ~ /->/ {
+       if (starts[$1] > 0) {
+          latency_ms = 1000 * (time - starts[$1])
+           if (opt_start)
+              printf "%-15s ", starts[$1]
+           if (opt_end)
+              printf "%-15s ", time
+
+           fd = fds[$1]
+
+           printf "%-12.12s %-6s %-4s %8s\n",
+               comm, pid, fd, latency_ms
+           if (!opt_duration)
+              fflush()
+
+           delete starts[$1]
+           delete fds[$1]
+       }
        next
     }
 
-   # exit pread
-   $1 != "#" && $0 ~ "->" {
-      if (starts[$1] > 0) {
-         latency_ms = 1000 * (time - starts[$1])
-          if (opt_start)
-             printf "%-15s ", starts[$1]
-          if (opt_end)
-             printf "%-15s ", time
-
-          fd = fds[$1]
-
-          printf "%-12.12s %-6s %-4s %8s\n",
-              comm, pid, fd, latency_ms
-          if (!opt_duration)
-             fflush()
-
-          delete starts[$1]
-          delete fds[$1]
-      }
-      next
-   }
-
-   $0 ~ /LOST.*EVENTS/ { print "WARNING: " $0 > "/dev/stderr" }
+    $0 ~ /LOST.*EVENTS/ { print "WARNING: " $0 > "/dev/stderr" }
 '
 
 ### end tracing
diff --git a/syscalls/pread64snoop b/syscalls/pread64snoop
--- a/syscalls/pread64snoop
+++ b/syscalls/pread64snoop
@@ -6,77 +6,77 @@ mkdir $tracing
 bufsize_kb=409600
 opt_duration=0; duration=; opt_name=0; name=; opt_pid=0; pid=; ftext=
 opt_start=0; opt_end=0; 
-trap ':' INT QUIT TERM PIPE HUP	# sends execution to end tracing section
+trap ':' INT QUIT TERM PIPE HUP    # sends execution to end tracing section
 
 function usage {
-	cat <<-END >&2
-	USAGE: pread64snoop [-hst] [-n name]
-	               [duratrwn]
-	                 -n name         # process name to match on pread issue
-	                 -s              # include start time of pread64 (s)
-	                 -t              # include completrwn time of prad64 (s)
-	                 -h              # this usage message
-	                 duratrwn        # duratrwn seconds, and use buffers
-	  eg,
-	       pread64snoop                   # watch pread64 live (unbuffered)
-	       pread64snoop 1                 # trace 1 sec (buffered)
-	       pread64snoop -ts               # include start and end timestamps
+    cat <<-END >&2
+    USAGE: pread64snoop [-hst] [-n name]
+                   [duratrwn]
+                     -n name         # process name to match on pread issue
+                     -s              # include start time of pread64 (s)
+                     -t              # include completrwn time of prad64 (s)
+                     -h              # this usage message
+                     duratrwn        # duratrwn seconds, and use buffers
+      eg,
+           pread64snoop                   # watch pread64 live (unbuffered)
+           pread64snoop 1                 # trace 1 sec (buffered)
+           pread64snoop -ts               # include start and end timestamps
 
-	See the man page and example file for more info.
+    See the man page and example file for more info.
 END
-	exit
+    exit
 }
 
 function warn {
-	if ! eval "$@"; then
-		echo >&2 "WARNING: command failed \"$@\""
-	fi
+    if ! eval "$@"; then
+        echo >&2 "WARNING: command failed \"$@\""
+    fi
 }
 
 function end {
-	# disable tracing
-	echo 2>/dev/null
-	echo "Ending tracing..." 2>/dev/null
-	cd $tracing
-	warn "echo 0 > events/syscalls/sys_enter_pread64/enable"
-	warn "echo 0 > events/syscalls/sys_exit_pread64/enable"
-	warn "echo > trace"
+    # disable tracing
+    echo 2>/dev/null
+    echo "Ending tracing..." 2>/dev/null
+    cd $tracing
+    warn "echo 0 > events/syscalls/sys_enter_pread64/enable"
+    warn "echo 0 > events/syscalls/sys_exit_pread64/enable"
+    warn "echo > trace"
     rmdir $tracing
 }
 
 function die {
-	echo >&2 "$@"
-	exit 1
+    echo >&2 "$@"
+    exit 1
 }
 
 function edie {
-	# die with a quiet end()
-	echo >&2 "$@"
-	exec >/dev/null 2>&1
-	end
-	exit 1
+    # die with a quiet end()
+    echo >&2 "$@"
+    exec >/dev/null 2>&1
+    end
+    exit 1
 }
 
 ### process options
 while getopts d:ha:n:p:Qst opt
 do
-	case $opt in
-	n)	opt_name=1; name=$OPTARG ;;
-	p)	opt_pid=1; pid=$OPTARG ;;
-	s)	opt_start=1 ;;
-	t)	opt_end=1 ;;
-	h|?)	usage ;;
-	esac
+    case $opt in
+    n)    opt_name=1; name=$OPTARG ;;
+    p)    opt_pid=1; pid=$OPTARG ;;
+    s)    opt_start=1 ;;
+    t)    opt_end=1 ;;
+    h|?)    usage ;;
+    esac
 done
 shift $(( $OPTIND - 1 ))
 if (( $# )); then
-	opt_duration=1
-	duration=$1
-	shift
+    opt_duration=1
+    duration=$1
+    shift
 fi
 
 ### select awk
-(( opt_duration )) && use=mawk || use=gawk	# workaround for mawk fflush()
+(( opt_duration )) && use=mawk || use=gawk    # workaround for mawk fflush()
 [[ -x /usr/bin/$use ]] && awk=$use || awk=awk
 wroteflock=1
 
@@ -90,7 +90,7 @@ warn "echo $bufsize_kb > buffer_size_kb"
 
 if ! echo 1 > events/syscalls/sys_enter_pread64/enable || \
     ! echo 1 > events/syscalls/sys_exit_pread64/enable; then
-	edie "ERROR: enabling block I/O tracepoints. Exiting."
+    edie "ERROR: enabling block I/O tracepoints. Exiting."
 fi
 (( opt_start )) && printf "%-15s " "STARTs"
 (( opt_end )) && printf "%-15s " "ENDs"
@@ -105,44 +105,48 @@ printf "%-12.12s %-6s %-4s  %-6s %8s\n" \
 # and an offset set, to skip the extra column when needed.
 #
 offset=$($awk 'BEGIN { o = 0; }
-	$1 == "#" && $2 ~ /TASK/ && NF == 6 { o = 1; }
-	$2 ~ /TASK/ { print o; exit }' trace)
+    $1 == "#" && $2 ~ /TASK/ && NF == 6 { o = 1; }
+    $2 ~ /TASK/ { print o; exit }' trace)
 
 ### print trace buffer
 warn "echo > trace"
 ( if (( opt_duration )); then
-	# wait then dump buffer
-	sleep $duration
-	cat trace
+    # wait then dump buffer
+    sleep $duration
+    cat trace
 else
-	# print buffer live
-	cat trace_pipe
+    # print buffer live
+    cat trace_pipe
 fi ) | $awk -v o=$offset -v opt_name=$opt_name -v name=$name \
     -v opt_duration=$opt_duration -v opt_start=$opt_start -v opt_end=$opt_end '
-	# common fields
-	$1 != "#" {
-		# task name can contain dashes
-		comm = pid = $1
-		sub(/-[0-9][0-9]*/, "", comm)
-		sub(/.*-/, "", pid)
-		time = $(3+o); sub(":", "", time)
-	}
+    # common fields
+    $1 != "#" {
+        # task name can contain dashes
+        comm = pid = $1
+        sub(/-[0-9][0-9]*/, "", comm)
+        sub(/.*-/, "", pid)
+        time = $(3+o); sub(":", "", time)
+
+        print $0
+    }
 
     # enter pread 
-    $1 != "#" && $0 ~ fd {
+    $1 != "#" && $0 ~ /sys_pread64/ && $(5+o) !~ /->/ {
        if (opt_name && match(comm, name) == 0)
           next
 
        count = $(NF-2)
+       sub(/,$/, "", count)
        fd=$(5+o)
+       sub(/\)$/, "", fd)
+       fd = strtonum("0x"fd)
        starts[$1] = time
        counts[$1] = count
        fds[$1] = fd
-       next
     }
 
    # exit pread
-   $1 != "#" && $0 ~ "->" {
+   $1 != "#" && $0 ~ /->/ {
       if (starts[$1] > 0) {
          latency_ms = 1000 * (time - starts[$1])
           if (opt_start)
